<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mCountry')->insert([
            [
                'id' => 34,
                'iso2' => "BV",
                'iso3' => "BVT",
                'name' => "Bouvet Island",
                'ison' => "074",
                'internationalPhoneCode' => NULL
            ],

            ['id' => 96, 'iso2' => "HM", 'iso3' => "HMD", 'name' => "Heard Island and McDonald Islands", 'ison' => "334", 'internationalPhoneCode' => NULL],
            ['id' => 18, 'iso2' => "BB", 'iso3' => "BRB", 'name' => "Barbados", 'ison' => "052", 'internationalPhoneCode' => "1246"],
            ['id' => 36, 'iso2' => "BY", 'iso3' => "BLR", 'name' => "Belarus", 'ison' => "112", 'internationalPhoneCode' => "375"],
            ['id' => 27, 'iso2' => "BM", 'iso3' => "BMU", 'name' => "Bermuda", 'ison' => "060", 'internationalPhoneCode' => "1441"],
            ['id' => 33, 'iso2' => "BT", 'iso3' => "BTN", 'name' => "Bhutan", 'ison' => "064", 'internationalPhoneCode' => "975"],
            ['id' => 29, 'iso2' => "BO", 'iso3' => "BOL", 'name' => "Bolivia, Plurinational State of", 'ison' => "068", 'internationalPhoneCode' => "591"],
            ['id' => 35, 'iso2' => "BW", 'iso3' => "BWA", 'name' => "Botswana", 'ison' => "072", 'internationalPhoneCode' => "267"],
            ['id' => 31, 'iso2' => "BR", 'iso3' => "BRA", 'name' => "Brazil", 'ison' => "076", 'internationalPhoneCode' => "55"],
            ['id' => 28, 'iso2' => "BN", 'iso3' => "BRN", 'name' => "Brunei Darussalam", 'ison' => "096", 'internationalPhoneCode' => "673"],
            ['id' => 52, 'iso2' => "CV", 'iso3' => "CPV", 'name' => "Cabo Verde", 'ison' => "132", 'internationalPhoneCode' => "238"],
            ['id' => 117, 'iso2' => "KH", 'iso3' => "KHM", 'name' => "Cambodia", 'ison' => "116", 'internationalPhoneCode' => "855"],
            ['id' => 47, 'iso2' => "CM", 'iso3' => "CMR", 'name' => "Cameroon", 'ison' => "120", 'internationalPhoneCode' => "237"],
            ['id' => 38, 'iso2' => "CA", 'iso3' => "CAN", 'name' => "Canada", 'ison' => "124", 'internationalPhoneCode' => "1"],
            ['id' => 41, 'iso2' => "CF", 'iso3' => "CAF", 'name' => "Central African Republic", 'ison' => "140", 'internationalPhoneCode' => "236"],
            ['id' => 124, 'iso2' => "KY", 'iso3' => "CYM", 'name' => "Cayman Islands", 'ison' => "136", 'internationalPhoneCode' => "1345"],
            ['id' => 46, 'iso2' => "CL", 'iso3' => "CHL", 'name' => "Chile", 'ison' => "152", 'internationalPhoneCode' => "56"],
            ['id' => 48, 'iso2' => "CN", 'iso3' => "CHN", 'name' => "China", 'ison' => "156", 'internationalPhoneCode' => "86"],
            ['id' => 54, 'iso2' => "CX", 'iso3' => "CXR", 'name' => "Christmas Island", 'ison' => "162", 'internationalPhoneCode' => "6189164"],
            ['id' => 49, 'iso2' => "CO", 'iso3' => "COL", 'name' => "Colombia", 'ison' => "170", 'internationalPhoneCode' => "57"],
            ['id' => 119, 'iso2' => "KM", 'iso3' => "COM", 'name' => "Comoros", 'ison' => "174", 'internationalPhoneCode' => "269"],
            ['id' => 42, 'iso2' => "CG", 'iso3' => "COG", 'name' => "Congo", 'ison' => "178", 'internationalPhoneCode' => "242"],
            ['id' => 40, 'iso2' => "CD", 'iso3' => "COD", 'name' => "Congo, the Democratic Republic of the", 'ison' => "180", 'internationalPhoneCode' => "243"],
            ['id' => 45, 'iso2' => "CK", 'iso3' => "COK", 'name' => "Cook Islands", 'ison' => "184", 'internationalPhoneCode' => "682"],
            ['id' => 50, 'iso2' => "CR", 'iso3' => "CRI", 'name' => "Costa Rica", 'ison' => "188", 'internationalPhoneCode' => "506"],
            ['id' => 44, 'iso2' => "CI", 'iso3' => "CIV", 'name' => "CÃ´te d Ivoire", 'ison' => "384", 'internationalPhoneCode' => "225"],
            ['id' => 98, 'iso2' => "HR", 'iso3' => "HRV", 'name' => "Croatia", 'ison' => "191", 'internationalPhoneCode' => "385"],
            ['id' => 51, 'iso2' => "CU", 'iso3' => "CUB", 'name' => "Cuba", 'ison' => "192", 'internationalPhoneCode' => "53"],
            ['id' => 56, 'iso2' => "CZ", 'iso3' => "CZE", 'name' => "Czech Republic", 'ison' => "203", 'internationalPhoneCode' => "420"],
            ['id' => 59, 'iso2' => "DK", 'iso3' => "DNK", 'name' => "Denmark", 'ison' => "208", 'internationalPhoneCode' => "45"],
            ['id' => 58, 'iso2' => "DJ", 'iso3' => "DJI", 'name' => "Djibouti", 'ison' => "262", 'internationalPhoneCode' => "253"],
            ['id' => 60, 'iso2' => "DM", 'iso3' => "DMA", 'name' => "Dominica", 'ison' => "212", 'internationalPhoneCode' => "1767"],
            ['id' => 61, 'iso2' => "DO", 'iso3' => "DOM", 'name' => "Dominican Republic", 'ison' => "214", 'internationalPhoneCode' => "1809"],
            ['id' => 63, 'iso2' => "EC", 'iso3' => "ECU", 'name' => "Ecuador", 'ison' => "218", 'internationalPhoneCode' => "593"],
            ['id' => 67, 'iso2' => "ER", 'iso3' => "ERI", 'name' => "Eritrea", 'ison' => "232", 'internationalPhoneCode' => "291"],
            ['id' => 64, 'iso2' => "EE", 'iso3' => "EST", 'name' => "Estonia", 'ison' => "233", 'internationalPhoneCode' => "372"],
            ['id' => 69, 'iso2' => "ET", 'iso3' => "ETH", 'name' => "Ethiopia", 'ison' => "231", 'internationalPhoneCode' => "251"],
            ['id' => 72, 'iso2' => "FK", 'iso3' => "FLK", 'name' => "Falkland Islands (Malvinas)", 'ison' => "238", 'internationalPhoneCode' => "500"],
            ['id' => 74, 'iso2' => "FO", 'iso3' => "FRO", 'name' => "Faroe Islands", 'ison' => "234", 'internationalPhoneCode' => "298"],
            ['id' => 71, 'iso2' => "FJ", 'iso3' => "FJI", 'name' => "Fiji", 'ison' => "242", 'internationalPhoneCode' => "679"],
            ['id' => 70, 'iso2' => "FI", 'iso3' => "FIN", 'name' => "Finland", 'ison' => "246", 'internationalPhoneCode' => "358"],
            ['id' => 75, 'iso2' => "FR", 'iso3' => "FRA", 'name' => "France", 'ison' => "250", 'internationalPhoneCode' => "33"],
            ['id' => 76, 'iso2' => "GA", 'iso3' => "GAB", 'name' => "Gabon", 'ison' => "266", 'internationalPhoneCode' => "241"],
            ['id' => 85, 'iso2' => "GM", 'iso3' => "GMB", 'name' => "Gambia", 'ison' => "270", 'internationalPhoneCode' => "220"],
            ['id' => 79, 'iso2' => "GE", 'iso3' => "GEO", 'name' => "Georgia", 'ison' => "268", 'internationalPhoneCode' => "995"],
            ['id' => 57, 'iso2' => "DE", 'iso3' => "DEU", 'name' => "Germany", 'ison' => "276", 'internationalPhoneCode' => "49"],
            ['id' => 82, 'iso2' => "GH", 'iso3' => "GHA", 'name' => "Ghana", 'ison' => "288", 'internationalPhoneCode' => "233"],
            ['id' => 83, 'iso2' => "GI", 'iso3' => "GIB", 'name' => "Gibraltar", 'ison' => "292", 'internationalPhoneCode' => "350"],
            ['id' => 89, 'iso2' => "GR", 'iso3' => "GRC", 'name' => "Greece", 'ison' => "300", 'internationalPhoneCode' => "30"],
            ['id' => 78, 'iso2' => "GD", 'iso3' => "GRD", 'name' => "Grenada", 'ison' => "308", 'internationalPhoneCode' => "1473"],
            ['id' => 87, 'iso2' => "GP", 'iso3' => "GLP", 'name' => "Guadeloupe", 'ison' => "312", 'internationalPhoneCode' => "590"],
            ['id' => 92, 'iso2' => "GU", 'iso3' => "GUM", 'name' => "Guam", 'ison' => "316", 'internationalPhoneCode' => "1671"],
            ['id' => 91, 'iso2' => "GT", 'iso3' => "GTM", 'name' => "Guatemala", 'ison' => "320", 'internationalPhoneCode' => "502"],
            ['id' => 86, 'iso2' => "GN", 'iso3' => "GIN", 'name' => "Guinea", 'ison' => "324", 'internationalPhoneCode' => "224"],
            ['id' => 94, 'iso2' => "GY", 'iso3' => "GUY", 'name' => "Guyana", 'ison' => "328", 'internationalPhoneCode' => "592"],
            ['id' => 99, 'iso2' => "HT", 'iso3' => "HTI", 'name' => "Haiti", 'ison' => "332", 'internationalPhoneCode' => "509"],
            ['id' => 155, 'iso2' => "MV", 'iso3' => "MDV", 'name' => "Maldives", 'ison' => "462", 'internationalPhoneCode' => "960"],
            ['id' => 145, 'iso2' => "ML", 'iso3' => "MLI", 'name' => "Mali", 'ison' => "466", 'internationalPhoneCode' => "223"],
            ['id' => 153, 'iso2' => "MT", 'iso3' => "MLT", 'name' => "Malta", 'ison' => "470", 'internationalPhoneCode' => "356"],
            ['id' => 150, 'iso2' => "MQ", 'iso3' => "MTQ", 'name' => "Martinique", 'ison' => "474", 'internationalPhoneCode' => "596"],
            ['id' => 151, 'iso2' => "MR", 'iso3' => "MRT", 'name' => "Mauritania", 'ison' => "478", 'internationalPhoneCode' => "222"],
            ['id' => 154, 'iso2' => "MU", 'iso3' => "MUS", 'name' => "Mauritius", 'ison' => "480", 'internationalPhoneCode' => "230"],
            ['id' => 157, 'iso2' => "MX", 'iso3' => "MEX", 'name' => "Mexico", 'ison' => "484", 'internationalPhoneCode' => "52"],
            ['id' => 139, 'iso2' => "MD", 'iso3' => "MDA", 'name' => "Moldova, Republic of", 'ison' => "498", 'internationalPhoneCode' => "373"],
            ['id' => 138, 'iso2' => "MC", 'iso3' => "MCO", 'name' => "Monaco", 'ison' => "492", 'internationalPhoneCode' => "377"],
            ['id' => 147, 'iso2' => "MN", 'iso3' => "MNG", 'name' => "Mongolia", 'ison' => "496", 'internationalPhoneCode' => "976"],
            ['id' => 140, 'iso2' => "ME", 'iso3' => "MNE", 'name' => "Montenegro", 'ison' => "499", 'internationalPhoneCode' => "382"],
            ['id' => 152, 'iso2' => "MS", 'iso3' => "MSR", 'name' => "Montserrat", 'ison' => "500", 'internationalPhoneCode' => "1664"],
            ['id' => 137, 'iso2' => "MA", 'iso3' => "MAR", 'name' => "Morocco", 'ison' => "504", 'internationalPhoneCode' => "212"],
            ['id' => 159, 'iso2' => "MZ", 'iso3' => "MOZ", 'name' => "Mozambique", 'ison' => "508", 'internationalPhoneCode' => "258"],
            ['id' => 146, 'iso2' => "MM", 'iso3' => "MMR", 'name' => "Myanmar", 'ison' => "104", 'internationalPhoneCode' => "95"],
            ['id' => 130, 'iso2' => "LK", 'iso3' => "LKA", 'name' => "Sri Lanka", 'ison' => "144", 'internationalPhoneCode' => "94"],
            ['id' => 221, 'iso2' => "TL", 'iso3' => "TLS", 'name' => "Timor-Leste", 'ison' => "626", 'internationalPhoneCode' => NULL],
            ['id' => 66, 'iso2' => "EH", 'iso3' => "ESH", 'name' => "Western Sahara", 'ison' => "732", 'internationalPhoneCode' => NULL],
            ['id' => 15, 'iso2' => "AX", 'iso3' => "ALA", 'name' => "Ã…land Islands", 'ison' => "248", 'internationalPhoneCode' => "35818"],
            ['id' => 6, 'iso2' => "AL", 'iso3' => "ALB", 'name' => "Albania", 'ison' => "008", 'internationalPhoneCode' => "355"],
            ['id' => 8, 'iso2' => "AO", 'iso3' => "AGO", 'name' => "Angola", 'ison' => "024", 'internationalPhoneCode' => "244"],
            ['id' => 5, 'iso2' => "AI", 'iso3' => "AIA", 'name' => "Anguilla", 'ison' => "660", 'internationalPhoneCode' => "1264"],
            ['id' => 4, 'iso2' => "AG", 'iso3' => "ATG", 'name' => "Antigua and Barbuda", 'ison' => "028", 'internationalPhoneCode' => "1268"],
            ['id' => 9, 'iso2' => "AQ", 'iso3' => "ATA", 'name' => "Antarctica", 'ison' => "010", 'internationalPhoneCode' => NULL],
            ['id' => 10, 'iso2' => "AR", 'iso3' => "ARG", 'name' => "Argentina", 'ison' => "032", 'internationalPhoneCode' => "54"],
            ['id' => 7, 'iso2' => "AM", 'iso3' => "ARM", 'name' => "Armenia", 'ison' => "051", 'internationalPhoneCode' => "374"],
            ['id' => 14, 'iso2' => "AW", 'iso3' => "ABW", 'name' => "Aruba", 'ison' => "533", 'internationalPhoneCode' => "297"],
            ['id' => 13, 'iso2' => "AU", 'iso3' => "AUS", 'name' => "Australia", 'ison' => "036", 'internationalPhoneCode' => "61"],
            ['id' => 16, 'iso2' => "AZ", 'iso3' => "AZE", 'name' => "Azerbaijan", 'ison' => "031", 'internationalPhoneCode' => "994"],
            ['id' => 23, 'iso2' => "BH", 'iso3' => "BHR", 'name' => "Bahrain", 'ison' => "048", 'internationalPhoneCode' => "973"],
            ['id' => 19, 'iso2' => "BD", 'iso3' => "BGD", 'name' => "Bangladesh", 'ison' => "050", 'internationalPhoneCode' => "880"],
            ['id' => 20, 'iso2' => "BE", 'iso3' => "BEL", 'name' => "Belgium", 'ison' => "056", 'internationalPhoneCode' => "32"],
            ['id' => 25, 'iso2' => "BJ", 'iso3' => "BEN", 'name' => "Benin", 'ison' => "204", 'internationalPhoneCode' => "229"],
            ['id' => 17, 'iso2' => "BA", 'iso3' => "BIH", 'name' => "Bosnia and Herzegovina", 'ison' => "070", 'internationalPhoneCode' => "387"],
            ['id' => 239, 'iso2' => "VG", 'iso3' => "VGB", 'name' => "Virgin Islands, British", 'ison' => "092", 'internationalPhoneCode' => "1284"],
            ['id' => 22, 'iso2' => "BG", 'iso3' => "BGR", 'name' => "Bulgaria", 'ison' => "100", 'internationalPhoneCode' => "359"],
            ['id' => 21, 'iso2' => "BF", 'iso3' => "BFA", 'name' => "Burkina Faso", 'ison' => "854", 'internationalPhoneCode' => "226"],
            ['id' => 24, 'iso2' => "BI", 'iso3' => "BDI", 'name' => "Burundi", 'ison' => "108", 'internationalPhoneCode' => "257"],
            ['id' => 215, 'iso2' => "TD", 'iso3' => "TCD", 'name' => "Chad", 'ison' => "148", 'internationalPhoneCode' => "235"],
            ['id' => 53, 'iso2' => "CW", 'iso3' => "CUW", 'name' => "CuraÃ§ao", 'ison' => "531", 'internationalPhoneCode' => "5999"],
            ['id' => 65, 'iso2' => "EG", 'iso3' => "EGY", 'name' => "Egypt", 'ison' => "818", 'internationalPhoneCode' => "20"],
            ['id' => 210, 'iso2' => "SV", 'iso3' => "SLV", 'name' => "El Salvador", 'ison' => "222", 'internationalPhoneCode' => "503"],
            ['id' => 175, 'iso2' => "PF", 'iso3' => "PYF", 'name' => "French Polynesia", 'ison' => "258", 'internationalPhoneCode' => "689"],
            ['id' => 216, 'iso2' => "TF", 'iso3' => "ATF", 'name' => "French Southern Territories", 'ison' => "260", 'internationalPhoneCode' => "596"],
            ['id' => 81, 'iso2' => "GG", 'iso3' => "GGY", 'name' => "Guernsey", 'ison' => "831", 'internationalPhoneCode' => "441481"],
            ['id' => 104, 'iso2' => "IM", 'iso3' => "IMN", 'name' => "Isle of Man", 'ison' => "833", 'internationalPhoneCode' => "441624"],
            ['id' => 143, 'iso2' => "MH", 'iso3' => "MHL", 'name' => "Marshall Islands", 'ison' => "584", 'internationalPhoneCode' => "692"],
            ['id' => 246, 'iso2' => "YT", 'iso3' => "MYT", 'name' => "Mayotte", 'ison' => "175", 'internationalPhoneCode' => "262269"],
            ['id' => 73, 'iso2' => "FM", 'iso3' => "FSM", 'name' => "Micronesia, Federated States of", 'ison' => "583", 'internationalPhoneCode' => "691"],
            ['id' => 149, 'iso2' => "MP", 'iso3' => "MNP", 'name' => "Northern Mariana Islands", 'ison' => "580", 'internationalPhoneCode' => "1670"],
            ['id' => 174, 'iso2' => "PE", 'iso3' => "PER", 'name' => "Peru", 'ison' => "604", 'internationalPhoneCode' => "51"],
            ['id' => 177, 'iso2' => "PH", 'iso3' => "PHL", 'name' => "Philippines", 'ison' => "608", 'internationalPhoneCode' => "63"],
            ['id' => 181, 'iso2' => "PN", 'iso3' => "PCN", 'name' => "Pitcairn", 'ison' => "612", 'internationalPhoneCode' => "64"],
            ['id' => 179, 'iso2' => "PL", 'iso3' => "POL", 'name' => "Poland", 'ison' => "616", 'internationalPhoneCode' => "48"],
            ['id' => 184, 'iso2' => "PT", 'iso3' => "PRT", 'name' => "Portugal", 'ison' => "620", 'internationalPhoneCode' => "351"],
            ['id' => 182, 'iso2' => "PR", 'iso3' => "PRI", 'name' => "Puerto Rico", 'ison' => "630", 'internationalPhoneCode' => "1787"],
            ['id' => 187, 'iso2' => "QA", 'iso3' => "QAT", 'name' => "Qatar", 'ison' => "634", 'internationalPhoneCode' => "974"],
            ['id' => 188, 'iso2' => "RE", 'iso3' => "REU", 'name' => "RÃ©union", 'ison' => "638", 'internationalPhoneCode' => "262"],
            ['id' => 189, 'iso2' => "RO", 'iso3' => "ROU", 'name' => "Romania", 'ison' => "642", 'internationalPhoneCode' => "40"],
            ['id' => 191, 'iso2' => "RU", 'iso3' => "RUS", 'name' => "Russian Federation", 'ison' => "643", 'internationalPhoneCode' => "7"],
            ['id' => 192, 'iso2' => "RW", 'iso3' => "RWA", 'name' => "Rwanda", 'ison' => "646", 'internationalPhoneCode' => "250"],
            ['id' => 26, 'iso2' => "BL", 'iso3' => "BLM", 'name' => "Saint BarthÃ©lemy", 'ison' => "652", 'internationalPhoneCode' => "590"],
            ['id' => 199, 'iso2' => "SH", 'iso3' => "SHN", 'name' => "Saint Helena, Ascension and Tristan da Cunha", 'ison' => "654", 'internationalPhoneCode' => "290"],
            ['id' => 120, 'iso2' => "KN", 'iso3' => "KNA", 'name' => "Saint Kitts and Nevis", 'ison' => "659", 'internationalPhoneCode' => "1869"],
            ['id' => 128, 'iso2' => "LC", 'iso3' => "LCA", 'name' => "Saint Lucia", 'ison' => "662", 'internationalPhoneCode' => "1758"],
            ['id' => 141, 'iso2' => "MF", 'iso3' => "MAF", 'name' => "Saint Martin (French part)", 'ison' => "663", 'internationalPhoneCode' => "590"],
            ['id' => 180, 'iso2' => "PM", 'iso3' => "SPM", 'name' => "Saint Pierre and Miquelon", 'ison' => "666", 'internationalPhoneCode' => "508"],
            ['id' => 237, 'iso2' => "VC", 'iso3' => "VCT", 'name' => "Saint Vincent and the Grenadines", 'ison' => "670", 'internationalPhoneCode' => "1784"],
            ['id' => 244, 'iso2' => "WS", 'iso3' => "WSM", 'name' => "Samoa", 'ison' => "882", 'internationalPhoneCode' => "685"],
            ['id' => 204, 'iso2' => "SM", 'iso3' => "SMR", 'name' => "San Marino", 'ison' => "674", 'internationalPhoneCode' => "378"],
            ['id' => 209, 'iso2' => "ST", 'iso3' => "STP", 'name' => "Sao Tome and Principe", 'ison' => "678", 'internationalPhoneCode' => "239"],
            ['id' => 193, 'iso2' => "SA", 'iso3' => "SAU", 'name' => "Saudi Arabia", 'ison' => "682", 'internationalPhoneCode' => "966"],
            ['id' => 205, 'iso2' => "SN", 'iso3' => "SEN", 'name' => "Senegal", 'ison' => "686", 'internationalPhoneCode' => "221"],
            ['id' => 195, 'iso2' => "SC", 'iso3' => "SYC", 'name' => "Seychelles", 'ison' => "690", 'internationalPhoneCode' => "248"],
            ['id' => 203, 'iso2' => "SL", 'iso3' => "SLE", 'name' => "Sierra Leone", 'ison' => "694", 'internationalPhoneCode' => "232"],
            ['id' => 198, 'iso2' => "SG", 'iso3' => "SGP", 'name' => "Singapore", 'ison' => "702", 'internationalPhoneCode' => "65"],
            ['id' => 202, 'iso2' => "SK", 'iso3' => "SVK", 'name' => "Slovakia", 'ison' => "703", 'internationalPhoneCode' => "421"],
            ['id' => 200, 'iso2' => "SI", 'iso3' => "SVN", 'name' => "Slovenia", 'ison' => "705", 'internationalPhoneCode' => "386"],
            ['id' => 194, 'iso2' => "SB", 'iso3' => "SLB", 'name' => "Solomon Islands", 'ison' => "090", 'internationalPhoneCode' => "677"],
            ['id' => 206, 'iso2' => "SO", 'iso3' => "SOM", 'name' => "Somalia", 'ison' => "706", 'internationalPhoneCode' => "252"],
            ['id' => 247, 'iso2' => "ZA", 'iso3' => "ZAF", 'name' => "South Africa", 'ison' => "710", 'internationalPhoneCode' => "27"],
            ['id' => 208, 'iso2' => "SS", 'iso3' => "SSD", 'name' => "South Sudan", 'ison' => "728", 'internationalPhoneCode' => "211"],
            ['id' => 68, 'iso2' => "ES", 'iso3' => "ESP", 'name' => "Spain", 'ison' => "724", 'internationalPhoneCode' => "34"],
            ['id' => 196, 'iso2' => "SD", 'iso3' => "SDN", 'name' => "Sudan", 'ison' => "729", 'internationalPhoneCode' => "249"],
            ['id' => 207, 'iso2' => "SR", 'iso3' => "SUR", 'name' => "Suriname", 'ison' => "740", 'internationalPhoneCode' => "597"],
            ['id' => 201, 'iso2' => "SJ", 'iso3' => "SJM", 'name' => "Svalbard and Jan Mayen", 'ison' => "744", 'internationalPhoneCode' => "4779"],
            ['id' => 213, 'iso2' => "SZ", 'iso3' => "SWZ", 'name' => "Swaziland", 'ison' => "748", 'internationalPhoneCode' => "268"],
            ['id' => 197, 'iso2' => "SE", 'iso3' => "SWE", 'name' => "Sweden", 'ison' => "752", 'internationalPhoneCode' => "46"],
            ['id' => 43, 'iso2' => "CH", 'iso3' => "CHE", 'name' => "Switzerland", 'ison' => "756", 'internationalPhoneCode' => "41"],
            ['id' => 212, 'iso2' => "SY", 'iso3' => "SYR", 'name' => "Syrian Arab Republic", 'ison' => "760", 'internationalPhoneCode' => "963"],
            ['id' => 228, 'iso2' => "TW", 'iso3' => "TWN", 'name' => "Taiwan, Province of China", 'ison' => "158", 'internationalPhoneCode' => "886"],
            ['id' => 219, 'iso2' => "TJ", 'iso3' => "TJK", 'name' => "Tajikistan", 'ison' => "762", 'internationalPhoneCode' => "992"],
            ['id' => 229, 'iso2' => "TZ", 'iso3' => "TZA", 'name' => "Tanzania, United Republic of", 'ison' => "834", 'internationalPhoneCode' => "255"],
            ['id' => 218, 'iso2' => "TH", 'iso3' => "THA", 'name' => "Thailand", 'ison' => "764", 'internationalPhoneCode' => "66"],
            ['id' => 217, 'iso2' => "TG", 'iso3' => "TGO", 'name' => "Togo", 'ison' => "768", 'internationalPhoneCode' => "228"],
            ['id' => 220, 'iso2' => "TK", 'iso3' => "TKL", 'name' => "Tokelau", 'ison' => "772", 'internationalPhoneCode' => "690"],
            ['id' => 226, 'iso2' => "TT", 'iso3' => "TTO", 'name' => "Trinidad and Tobago", 'ison' => "780", 'internationalPhoneCode' => "1868"],
            ['id' => 223, 'iso2' => "TN", 'iso3' => "TUN", 'name' => "Tunisia", 'ison' => "788", 'internationalPhoneCode' => "216"],
            ['id' => 225, 'iso2' => "TR", 'iso3' => "TUR", 'name' => "Turkey", 'ison' => "792", 'internationalPhoneCode' => "90"],
            ['id' => 222, 'iso2' => "TM", 'iso3' => "TKM", 'name' => "Turkmenistan", 'ison' => "795", 'internationalPhoneCode' => "993"],
            ['id' => 214, 'iso2' => "TC", 'iso3' => "TCA", 'name' => "Turks and Caicos Islands", 'ison' => "796", 'internationalPhoneCode' => "1649"],
            ['id' => 227, 'iso2' => "TV", 'iso3' => "TUV", 'name' => "Tuvalu", 'ison' => "798", 'internationalPhoneCode' => "688"],
            ['id' => 231, 'iso2' => "UG", 'iso3' => "UGA", 'name' => "Uganda", 'ison' => "800", 'internationalPhoneCode' => "256"],
            ['id' => 77, 'iso2' => "GB", 'iso3' => "GBR", 'name' => "United Kingdom", 'ison' => "826", 'internationalPhoneCode' => "44"],
            ['id' => 233, 'iso2' => "US", 'iso3' => "USA", 'name' => "United States", 'ison' => "840", 'internationalPhoneCode' => "1"],
            ['id' => 234, 'iso2' => "UY", 'iso3' => "URY", 'name' => "Uruguay", 'ison' => "858", 'internationalPhoneCode' => "598"],
            ['id' => 235, 'iso2' => "UZ", 'iso3' => "UZB", 'name' => "Uzbekistan", 'ison' => "860", 'internationalPhoneCode' => "998"],
            ['id' => 241, 'iso2' => "VN", 'iso3' => "VNM", 'name' => "Viet Nam", 'ison' => "704", 'internationalPhoneCode' => "84"],
            ['id' => 243, 'iso2' => "WF", 'iso3' => "WLF", 'name' => "Wallis and Futuna", 'ison' => "876", 'internationalPhoneCode' => "681"],
            ['id' => 245, 'iso2' => "YE", 'iso3' => "YEM", 'name' => "Yemen", 'ison' => "887", 'internationalPhoneCode' => "967"],
            ['id' => 248, 'iso2' => "ZM", 'iso3' => "ZMB", 'name' => "Zambia", 'ison' => "894", 'internationalPhoneCode' => "260"],
            ['id' => 249, 'iso2' => "ZW", 'iso3' => "ZWE", 'name' => "Zimbabwe", 'ison' => "716", 'internationalPhoneCode' => "263"],
            ['id' => 236, 'iso2' => "VA", 'iso3' => "VAT", 'name' => "Holy See (Vatican City State)", 'ison' => "336", 'internationalPhoneCode' => NULL],
            ['id' => 232, 'iso2' => "UM", 'iso3' => "UMI", 'name' => "United States Minor Outlying Islands", 'ison' => "581", 'internationalPhoneCode' => NULL],
            ['id' => 238, 'iso2' => "VE", 'iso3' => "VEN", 'name' => "Venezuela, Bolivarian Republic of", 'ison' => "862", 'internationalPhoneCode' => "58"],
            ['id' => 3, 'iso2' => "AF", 'iso3' => "AFG", 'name' => "Afghanistan", 'ison' => "004", 'internationalPhoneCode' => "93"],
            ['id' => 62, 'iso2' => "DZ", 'iso3' => "DZA", 'name' => "Algeria", 'ison' => "012", 'internationalPhoneCode' => "213"],
            ['id' => 11, 'iso2' => "AS", 'iso3' => "ASM", 'name' => "American Samoa", 'ison' => "016", 'internationalPhoneCode' => "1684"],
            ['id' => 1, 'iso2' => "AD", 'iso3' => "AND", 'name' => "Andorra", 'ison' => "020", 'internationalPhoneCode' => "376"],
            ['id' => 32, 'iso2' => "BS", 'iso3' => "BHS", 'name' => "Bahamas", 'ison' => "044", 'internationalPhoneCode' => "1242"],
            ['id' => 37, 'iso2' => "BZ", 'iso3' => "BLZ", 'name' => "Belize", 'ison' => "084", 'internationalPhoneCode' => "501"],
            ['id' => 30, 'iso2' => "BQ", 'iso3' => "BES", 'name' => "Bonaire, Sint Eustatius and Saba", 'ison' => "535", 'internationalPhoneCode' => "5997"],
            ['id' => 106, 'iso2' => "IO", 'iso3' => "IOT", 'name' => "British Indian Ocean Territory", 'ison' => "086", 'internationalPhoneCode' => "246"],
            ['id' => 39, 'iso2' => "CC", 'iso3' => "CCK", 'name' => "Cocos (Keeling) Islands", 'ison' => "166", 'internationalPhoneCode' => "6189162"],
            ['id' => 55, 'iso2' => "CY", 'iso3' => "CYP", 'name' => "Cyprus", 'ison' => "196", 'internationalPhoneCode' => "357"],
            ['id' => 88, 'iso2' => "GQ", 'iso3' => "GNQ", 'name' => "Equatorial Guinea", 'ison' => "226", 'internationalPhoneCode' => "240"],
            ['id' => 80, 'iso2' => "GF", 'iso3' => "GUF", 'name' => "French Guiana", 'ison' => "254", 'internationalPhoneCode' => "594"],
            ['id' => 84, 'iso2' => "GL", 'iso3' => "GRL", 'name' => "Greenland", 'ison' => "304", 'internationalPhoneCode' => "299"],
            ['id' => 93, 'iso2' => "GW", 'iso3' => "GNB", 'name' => "Guinea-Bissau", 'ison' => "624", 'internationalPhoneCode' => "245"],
            ['id' => 97, 'iso2' => "HN", 'iso3' => "HND", 'name' => "Honduras", 'ison' => "340", 'internationalPhoneCode' => "504"],
            ['id' => 95, 'iso2' => "HK", 'iso3' => "HKG", 'name' => "Hong Kong", 'ison' => "344", 'internationalPhoneCode' => "852"],
            ['id' => 100, 'iso2' => "HU", 'iso3' => "HUN", 'name' => "Hungary", 'ison' => "348", 'internationalPhoneCode' => "36"],
            ['id' => 109, 'iso2' => "IS", 'iso3' => "ISL", 'name' => "Iceland", 'ison' => "352", 'internationalPhoneCode' => "354"],
            ['id' => 105, 'iso2' => "IN", 'iso3' => "IND", 'name' => "India", 'ison' => "356", 'internationalPhoneCode' => "91"],
            ['id' => 101, 'iso2' => "ID", 'iso3' => "IDN", 'name' => "Indonesia", 'ison' => "360", 'internationalPhoneCode' => "62"],
            ['id' => 108, 'iso2' => "IR", 'iso3' => "IRN", 'name' => "Iran, Islamic Republic of", 'ison' => "364", 'internationalPhoneCode' => "98"],
            ['id' => 107, 'iso2' => "IQ", 'iso3' => "IRQ", 'name' => "Iraq", 'ison' => "368", 'internationalPhoneCode' => "964"],
            ['id' => 102, 'iso2' => "IE", 'iso3' => "IRL", 'name' => "Ireland", 'ison' => "372", 'internationalPhoneCode' => "353"],
            ['id' => 103, 'iso2' => "IL", 'iso3' => "ISR", 'name' => "Israel", 'ison' => "376", 'internationalPhoneCode' => "972"],
            ['id' => 110, 'iso2' => "IT", 'iso3' => "ITA", 'name' => "Italy", 'ison' => "380", 'internationalPhoneCode' => "39"],
            ['id' => 112, 'iso2' => "JM", 'iso3' => "JAM", 'name' => "Jamaica", 'ison' => "388", 'internationalPhoneCode' => "1876"],
            ['id' => 114, 'iso2' => "JP", 'iso3' => "JPN", 'name' => "Japan", 'ison' => "392", 'internationalPhoneCode' => "81"],
            ['id' => 111, 'iso2' => "JE", 'iso3' => "JEY", 'name' => "Jersey", 'ison' => "832", 'internationalPhoneCode' => "441534"],
            ['id' => 113, 'iso2' => "JO", 'iso3' => "JOR", 'name' => "Jordan", 'ison' => "400", 'internationalPhoneCode' => "962"],
            ['id' => 125, 'iso2' => "KZ", 'iso3' => "KAZ", 'name' => "Kazakhstan", 'ison' => "398", 'internationalPhoneCode' => "76"],
            ['id' => 115, 'iso2' => "KE", 'iso3' => "KEN", 'name' => "Kenya", 'ison' => "404", 'internationalPhoneCode' => "254"],
            ['id' => 118, 'iso2' => "KI", 'iso3' => "KIR", 'name' => "Kiribati", 'ison' => "296", 'internationalPhoneCode' => "686"],
            ['id' => 121, 'iso2' => "KP", 'iso3' => "PRK", 'name' => "Korea, Democratic People s Republic of", 'ison' => "408", 'internationalPhoneCode' => "82"],
            ['id' => 122, 'iso2' => "KR", 'iso3' => "KOR", 'name' => "Korea, Republic of", 'ison' => "410", 'internationalPhoneCode' => "850"],
            ['id' => 123, 'iso2' => "KW", 'iso3' => "KWT", 'name' => "Kuwait", 'ison' => "414", 'internationalPhoneCode' => "965"],
            ['id' => 116, 'iso2' => "KG", 'iso3' => "KGZ", 'name' => "Kyrgyzstan", 'ison' => "417", 'internationalPhoneCode' => "996"],
            ['id' => 126, 'iso2' => "LA", 'iso3' => "LAO", 'name' => "Lao People s Democratic Republic", 'ison' => "418", 'internationalPhoneCode' => "856"],
            ['id' => 135, 'iso2' => "LV", 'iso3' => "LVA", 'name' => "Latvia", 'ison' => "428", 'internationalPhoneCode' => "371"],
            ['id' => 127, 'iso2' => "LB", 'iso3' => "LBN", 'name' => "Lebanon", 'ison' => "422", 'internationalPhoneCode' => "961"],
            ['id' => 132, 'iso2' => "LS", 'iso3' => "LSO", 'name' => "Lesotho", 'ison' => "426", 'internationalPhoneCode' => "266"],
            ['id' => 131, 'iso2' => "LR", 'iso3' => "LBR", 'name' => "Liberia", 'ison' => "430", 'internationalPhoneCode' => "231"],
            ['id' => 136, 'iso2' => "LY", 'iso3' => "LBY", 'name' => "Libya", 'ison' => "434", 'internationalPhoneCode' => "218"],
            ['id' => 129, 'iso2' => "LI", 'iso3' => "LIE", 'name' => "Liechtenstein", 'ison' => "438", 'internationalPhoneCode' => "423"],
            ['id' => 133, 'iso2' => "LT", 'iso3' => "LTU", 'name' => "Lithuania", 'ison' => "440", 'internationalPhoneCode' => "370"],
            ['id' => 134, 'iso2' => "LU", 'iso3' => "LUX", 'name' => "Luxembourg", 'ison' => "442", 'internationalPhoneCode' => "352"],
            ['id' => 148, 'iso2' => "MO", 'iso3' => "MAC", 'name' => "Macao", 'ison' => "446", 'internationalPhoneCode' => "853"],
            ['id' => 144, 'iso2' => "MK", 'iso3' => "MKD", 'name' => "Macedonia, the former Yugoslav Republic of", 'ison' => "807", 'internationalPhoneCode' => "389"],
            ['id' => 142, 'iso2' => "MG", 'iso3' => "MDG", 'name' => "Madagascar", 'ison' => "450", 'internationalPhoneCode' => "261"],
            ['id' => 156, 'iso2' => "MW", 'iso3' => "MWI", 'name' => "Malawi", 'ison' => "454", 'internationalPhoneCode' => "265"],
            ['id' => 158, 'iso2' => "MY", 'iso3' => "MYS", 'name' => "Malaysia", 'ison' => "458", 'internationalPhoneCode' => "60"],
            ['id' => 160, 'iso2' => "NA", 'iso3' => "NAM", 'name' => "Namibia", 'ison' => "516", 'internationalPhoneCode' => "264"],
            ['id' => 169, 'iso2' => "NR", 'iso3' => "NRU", 'name' => "Nauru", 'ison' => "520", 'internationalPhoneCode' => "674"],
            ['id' => 168, 'iso2' => "NP", 'iso3' => "NPL", 'name' => "Nepal", 'ison' => "524", 'internationalPhoneCode' => "977"],
            ['id' => 166, 'iso2' => "NL", 'iso3' => "NLD", 'name' => "Netherlands", 'ison' => "528", 'internationalPhoneCode' => "31"],
            ['id' => 161, 'iso2' => "NC", 'iso3' => "NCL", 'name' => "New Caledonia", 'ison' => "540", 'internationalPhoneCode' => "687"],
            ['id' => 171, 'iso2' => "NZ", 'iso3' => "NZL", 'name' => "New Zealand", 'ison' => "554", 'internationalPhoneCode' => "64"],
            ['id' => 165, 'iso2' => "NI", 'iso3' => "NIC", 'name' => "Nicaragua", 'ison' => "558", 'internationalPhoneCode' => "505"],
            ['id' => 162, 'iso2' => "NE", 'iso3' => "NER", 'name' => "Niger", 'ison' => "562", 'internationalPhoneCode' => "227"],
            ['id' => 164, 'iso2' => "NG", 'iso3' => "NGA", 'name' => "Nigeria", 'ison' => "566", 'internationalPhoneCode' => "234"],
            ['id' => 170, 'iso2' => "NU", 'iso3' => "NIU", 'name' => "Niue", 'ison' => "570", 'internationalPhoneCode' => "683"],
            ['id' => 163, 'iso2' => "NF", 'iso3' => "NFK", 'name' => "Norfolk Island", 'ison' => "574", 'internationalPhoneCode' => "6723"],
            ['id' => 167, 'iso2' => "NO", 'iso3' => "NOR", 'name' => "Norway", 'ison' => "578", 'internationalPhoneCode' => "47"],
            ['id' => 172, 'iso2' => "OM", 'iso3' => "OMN", 'name' => "Oman", 'ison' => "512", 'internationalPhoneCode' => "968"],
            ['id' => 178, 'iso2' => "PK", 'iso3' => "PAK", 'name' => "Pakistan", 'ison' => "586", 'internationalPhoneCode' => "92"],
            ['id' => 185, 'iso2' => "PW", 'iso3' => "PLW", 'name' => "Palau", 'ison' => "585", 'internationalPhoneCode' => "680"],
            ['id' => 183, 'iso2' => "PS", 'iso3' => "PSE", 'name' => "Palestine, State of", 'ison' => "275", 'internationalPhoneCode' => "970"],
            ['id' => 173, 'iso2' => "PA", 'iso3' => "PAN", 'name' => "Panama", 'ison' => "591", 'internationalPhoneCode' => "507"],
            ['id' => 176, 'iso2' => "PG", 'iso3' => "PNG", 'name' => "Papua New Guinea", 'ison' => "598", 'internationalPhoneCode' => "675"],
            ['id' => 186, 'iso2' => "PY", 'iso3' => "PRY", 'name' => "Paraguay", 'ison' => "600", 'internationalPhoneCode' => "595"],
            ['id' => 190, 'iso2' => "RS", 'iso3' => "SRB", 'name' => "Serbia", 'ison' => "688", 'internationalPhoneCode' => "381"],
            ['id' => 211, 'iso2' => "SX", 'iso3' => "SXM", 'name' => "Sint Maarten (Dutch part)", 'ison' => "534", 'internationalPhoneCode' => "1721"],
            ['id' => 90, 'iso2' => "GS", 'iso3' => "SGS", 'name' => "South Georgia and the South Sandwich Islands", 'ison' => "239", 'internationalPhoneCode' => "500"],
            ['id' => 224, 'iso2' => "TO", 'iso3' => "TON", 'name' => "Tonga", 'ison' => "776", 'internationalPhoneCode' => "676"],
            ['id' => 230, 'iso2' => "UA", 'iso3' => "UKR", 'name' => "Ukraine", 'ison' => "804", 'internationalPhoneCode' => "380"],
            ['id' => 2, 'iso2' => "AE", 'iso3' => "ARE", 'name' => "United Arab Emirates", 'ison' => "784", 'internationalPhoneCode' => "971"],
            ['id' => 242, 'iso2' => "VU", 'iso3' => "VUT", 'name' => "Vanuatu", 'ison' => "548", 'internationalPhoneCode' => "678"],
            ['id' => 240, 'iso2' => "VI", 'iso3' => "VIR", 'name' => "Virgin Islands, U.S.", 'ison' => "850", 'internationalPhoneCode' => "1340"],
            ['id' => 12, 'iso2' => "AT", 'iso3' => "AUT", 'name' => "Austria", 'ison' =>  "040",  'internationalPhoneCode' => "43"],
        ]);
    }
}
