<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mState')->insert([
            ['id' => 1, 'iso' => "DO-01", 'name' => "Distrito NacionalÂ (Santo Domingo)", 'idCountry' => 61],
            ['id' => 3, 'iso' => "DO-03", 'name' => "Bahoruco", 'idCountry' => 61],
            ['id' => 4, 'iso' => "DO-04", 'name' => "Barahona", 'idCountry' => 61],
            ['id' => 5, 'iso' => "DO-05", 'name' => "DajabÃ³n", 'idCountry' => 61],
            ['id' => 6, 'iso' => "DO-06", 'name' => "Duarte", 'idCountry' => 61],
            ['id' => 7, 'iso' => "DO-08", 'name' => "El SeyboÂ [El Seibo]", 'idCountry' => 61],
            ['id' => 8, 'iso' => "DO-09", 'name' => "Espaillat", 'idCountry' => 61],
            ['id' => 9, 'iso' => "DO-30", 'name' => "Hato Mayor", 'idCountry' => 61],
            ['id' => 10, 'iso' => "DO-10", 'name' => "Independencia", 'idCountry' => 61],
            ['id' => 11, 'iso' => "DO-11", 'name' => "La Altagracia", 'idCountry' => 61],
            ['id' => 12, 'iso' => "DO-07", 'name' => "La EstrelletaÂ [ElÃ­as PiÃ±a]", 'idCountry' => 61],
            ['id' => 13, 'iso' => "DO-12", 'name' => "La Romana", 'idCountry' => 61],
            ['id' => 14, 'iso' => "DO-13", 'name' => "La Vega", 'idCountry' => 61],
            ['id' => 15, 'iso' => "DO-14", 'name' => "MarÃ­a Trinidad SÃ¡nchez", 'idCountry' => 61],
            ['id' => 17, 'iso' => "DO-15", 'name' => "Monte Cristi", 'idCountry' => 61],
            ['id' => 18, 'iso' => "DO-29", 'name' => "Monte Plata", 'idCountry' => 61],
            ['id' => 19, 'iso' => "DO-16", 'name' => "Pedernales", 'idCountry' => 61],
            ['id' => 20, 'iso' => "DO-17", 'name' => "Peravia", 'idCountry' => 61],
            ['id' => 21, 'iso' => "DO-18", 'name' => "Puerto Plata", 'idCountry' => 61],
            ['id' => 23, 'iso' => "DO-20", 'name' => "SamanÃ¡", 'idCountry' => 61],
            ['id' => 24, 'iso' => "DO-21", 'name' => "San CristÃ³bal", 'idCountry' => 61],
            ['id' => 25, 'iso' => "DO-31", 'name' => "San JosÃ© de Ocoa", 'idCountry' => 61],
            ['id' => 26, 'iso' => "DO-22", 'name' => "San Juan", 'idCountry' => 61],
            ['id' => 27, 'iso' => "DO-23", 'name' => "San Pedro de MacorÃ­s", 'idCountry' => 61],
            ['id' => 28, 'iso' => "DO-24", 'name' => "SÃ¡nchez RamÃ­rez", 'idCountry' => 61],
            ['id' => 29, 'iso' => "DO-25", 'name' => "Santiago", 'idCountry' => 61],
            ['id' => 30, 'iso' => "DO-26", 'name' => "Santiago RodrÃ­guez", 'idCountry' => 61],
            ['id' => 31, 'iso' => "DO-32", 'name' => "Santo Domingo", 'idCountry' => 61],
            ['id' => 32, 'iso' => "DO-27", 'name' => "Valverde", 'idCountry' => 61],
            ['id' => 34, 'iso' => "PA-4", 'name' => "ChiriquÃ­", 'idCountry' => 173],
            ['id' => 35, 'iso' => "PA-2", 'name' => "CoclÃ©", 'idCountry' => 173],
            ['id' => 36, 'iso' => "PA-3", 'name' => "ColÃ³n", 'idCountry' => 173],
            ['id' => 37, 'iso' => "PA-5", 'name' => "DariÃ©n", 'idCountry' => 173],
            ['id' => 38, 'iso' => "PA-6", 'name' => "Herrera", 'idCountry' => 173],
            ['id' => 39, 'iso' => "PA-7", 'name' => "Los Santos", 'idCountry' => 173],
            ['id' => 40, 'iso' => "PA-8", 'name' => "PanamÃ¡", 'idCountry' => 173],
            ['id' => 41, 'iso' => "PA-9", 'name' => "Veraguas", 'idCountry' => 173],
            ['id' => 42, 'iso' => "PA-EM", 'name' => "EmberÃ¡", 'idCountry' => 173],
            ['id' => 43, 'iso' => "PA-KY", 'name' => "Kuna Yala", 'idCountry' => 173],
            ['id' => 44, 'iso' => "PA-NB", 'name' => "NgÃ¶be-BuglÃ©Â ", 'idCountry' => 173],
            ['id' => 46, 'iso' => "US-AK", 'name' => "Alaska", 'idCountry' => 233],
            ['id' => 47, 'iso' => "US-AZ", 'name' => "Arizona", 'idCountry' => 233],
            ['id' => 48, 'iso' => "US-AR", 'name' => "Arkansas", 'idCountry' => 233],
            ['id' => 49, 'iso' => "US-CA", 'name' => "California", 'idCountry' => 233],
            ['id' => 50, 'iso' => "US-CO", 'name' => "Colorado", 'idCountry' => 233],
            ['id' => 51, 'iso' => "US-CT", 'name' => "Connecticut", 'idCountry' => 233],
            ['id' => 52, 'iso' => "US-DE", 'name' => "Delaware", 'idCountry' => 233],
            ['id' => 53, 'iso' => "US-FL", 'name' => "Florida", 'idCountry' => 233],
            ['id' => 54, 'iso' => "US-GA", 'name' => "Georgia", 'idCountry' => 233],
            ['id' => 55, 'iso' => "US-HI", 'name' => "Hawaii", 'idCountry' => 233],
            ['id' => 56, 'iso' => "US-ID", 'name' => "Idaho", 'idCountry' => 233],
            ['id' => 57, 'iso' => "US-IL", 'name' => "Illinois", 'idCountry' => 233],
            ['id' => 58, 'iso' => "US-IN", 'name' => "Indiana", 'idCountry' => 233],
            ['id' => 59, 'iso' => "US-IA", 'name' => "Iowa", 'idCountry' => 233],
            ['id' => 60, 'iso' => "US-KS", 'name' => "Kansas", 'idCountry' => 233],
            ['id' => 61, 'iso' => "US-KY", 'name' => "Kentucky", 'idCountry' => 233],
            ['id' => 62, 'iso' => "US-LA", 'name' => "Louisiana", 'idCountry' => 233],
            ['id' => 63, 'iso' => "US-ME", 'name' => "Maine", 'idCountry' => 233],
            ['id' => 64, 'iso' => "US-MD", 'name' => "Maryland", 'idCountry' => 233],
            ['id' => 65, 'iso' => "US-MA", 'name' => "Massachusetts", 'idCountry' => 233],
            ['id' => 66, 'iso' => "US-MI", 'name' => "Michigan", 'idCountry' => 233],
            ['id' => 67, 'iso' => "US-MN", 'name' => "Minnesota", 'idCountry' => 233],
            ['id' => 68, 'iso' => "US-MS", 'name' => "Mississippi", 'idCountry' => 233],
            ['id' => 69, 'iso' => "US-MO", 'name' => "Missouri", 'idCountry' => 233],
            ['id' => 70, 'iso' => "US-MT", 'name' => "Montana", 'idCountry' => 233],
            ['id' => 71, 'iso' => "US-NE", 'name' => "Nebraska", 'idCountry' => 233],
            ['id' => 72, 'iso' => "US-NV", 'name' => "Nevada", 'idCountry' => 233],
            ['id' => 73, 'iso' => "US-NH", 'name' => "New Hampshire", 'idCountry' => 233],
            ['id' => 74, 'iso' => "US-NJ", 'name' => "New Jersey", 'idCountry' => 233],
            ['id' => 75, 'iso' => "US-NM", 'name' => "New Mexico", 'idCountry' => 233],
            ['id' => 76, 'iso' => "US-NY", 'name' => "New York", 'idCountry' => 233],
            ['id' => 77, 'iso' => "US-NC", 'name' => "North Carolina", 'idCountry' => 233],
            ['id' => 78, 'iso' => "US-ND", 'name' => "North Dakota", 'idCountry' => 233],
            ['id' => 79, 'iso' => "US-OH", 'name' => "Ohio", 'idCountry' => 233],
            ['id' => 80, 'iso' => "US-OK", 'name' => "Oklahoma", 'idCountry' => 233],
            ['id' => 81, 'iso' => "US-OR", 'name' => "Oregon", 'idCountry' => 233],
            ['id' => 82, 'iso' => "US-PA", 'name' => "Pennsylvania", 'idCountry' => 233],
            ['id' => 83, 'iso' => "US-RI", 'name' => "Rhode Island", 'idCountry' => 233],
            ['id' => 84, 'iso' => "US-SC", 'name' => "South Carolina", 'idCountry' => 233],
            ['id' => 85, 'iso' => "US-SD", 'name' => "South Dakota", 'idCountry' => 233],
            ['id' => 86, 'iso' => "US-TN", 'name' => "Tennessee", 'idCountry' => 233],
            ['id' => 87, 'iso' => "US-TX", 'name' => "Texas", 'idCountry' => 233],
            ['id' => 88, 'iso' => "US-UT", 'name' => "Utah", 'idCountry' => 233],
            ['id' => 89, 'iso' => "US-VT", 'name' => "Vermont", 'idCountry' => 233],
            ['id' => 90, 'iso' => "US-VA", 'name' => "Virginia", 'idCountry' => 233],
            ['id' => 91, 'iso' => "US-WA", 'name' => "Washington", 'idCountry' => 233],
            ['id' => 92, 'iso' => "US-WV", 'name' => "West Virginia", 'idCountry' => 233],
            ['id' => 93, 'iso' => "US-WI", 'name' => "Wisconsin", 'idCountry' => 233],
            ['id' => 94, 'iso' => "US-WY", 'name' => "Wyoming", 'idCountry' => 233],
            ['id' => 95, 'iso' => "US-DC", 'name' => "District of Columbia", 'idCountry' => 233],
            ['id' => 96, 'iso' => "US-AS", 'name' => "American Samoa", 'idCountry' => 233],
            ['id' => 97, 'iso' => "US-GU", 'name' => "Guam", 'idCountry' => 233],
            ['id' => 98, 'iso' => "US-MP", 'name' => "Northern Mariana Islands", 'idCountry' => 233],
            ['id' => 99, 'iso' => "US-PR", 'name' => "Puerto Rico", 'idCountry' => 233],
            ['id' => 100, 'iso' => "US-UM", 'name' => "United States Minor Outlying I", 'idCountry' => 233],
            ['id' => 101, 'iso' => "US-VI", 'name' => "Virgin Islands, U.S.", 'idCountry' => 233],
            ['id' => 45, 'iso' => "US-AL", 'name' => "Alabama", 'idCountry' => 233],
            ['id' => 16, 'iso' => "DO-28", 'name' => "MonseÃ±or Nouel", 'idCountry' => 61],
            ['id' => 33, 'iso' => "PA-1", 'name' => "Bocas del Toro", 'idCountry' => 173],
            ['id' => 104, 'iso' => "ES-AR", 'name' => "AragÃ³n", 'idCountry' => 68],
            ['id' => 117, 'iso' => "ES-AS", 'name' => "Asturias, Principado de", 'idCountry' => 68],
            ['id' => 118, 'iso' => "ES-CN", 'name' => "Canarias", 'idCountry' => 68],
            ['id' => 119, 'iso' => "ES-CB", 'name' => "Cantabria", 'idCountry' => 68],
            ['id' => 120, 'iso' => "ES-CM", 'name' => "Castilla-La Mancha", 'idCountry' => 68],
            ['id' => 121, 'iso' => "ES-CL", 'name' => "Castilla y LeÃ³n", 'idCountry' => 68],
            ['id' => 122, 'iso' => "ES-CT", 'name' => "CatalunyaÂ (ca) [CataluÃ±a]", 'idCountry' => 68],
            ['id' => 123, 'iso' => "ES-EX", 'name' => "Extremadura", 'idCountry' => 68],
            ['id' => 124, 'iso' => "ES-GA", 'name' => "GaliciaÂ (gl) [Galicia]", 'idCountry' => 68],
            ['id' => 22, 'iso' => "DO-19", 'name' => "Salcedo (Hermanas Mirabal)", 'idCountry' => 61],
            ['id' => 134, 'iso' => "CO-AMA", 'name' => "Amazonas", 'idCountry' => 49],
            ['id' => 135, 'iso' => "CO-ANT", 'name' => "Antioquia", 'idCountry' => 49],
            ['id' => 136, 'iso' => "CO-ARA", 'name' => "Arauca", 'idCountry' => 49],
            ['id' => 137, 'iso' => "CO-ATL", 'name' => "AtlÃ¡ntico", 'idCountry' => 49],
            ['id' => 138, 'iso' => "CO-BOL", 'name' => "BolÃ­var", 'idCountry' => 49],
            ['id' => 139, 'iso' => "CO-BOY", 'name' => "BoyacÃ¡", 'idCountry' => 49],
            ['id' => 140, 'iso' => "CO-CAL", 'name' => "Caldas", 'idCountry' => 49],
            ['id' => 141, 'iso' => "CO-CAQ", 'name' => "CaquetÃ¡", 'idCountry' => 49],
            ['id' => 142, 'iso' => "CO-CAS", 'name' => "Casanare", 'idCountry' => 49],
            ['id' => 143, 'iso' => "CO-CAU", 'name' => "Cauca", 'idCountry' => 49],
            ['id' => 144, 'iso' => "CO-CES", 'name' => "Cesar", 'idCountry' => 49],
            ['id' => 145, 'iso' => "CO-CHO", 'name' => "ChocÃ³", 'idCountry' => 49],
            ['id' => 146, 'iso' => "CO-COR", 'name' => "CÃ³rdoba", 'idCountry' => 49],
            ['id' => 147, 'iso' => "CO-CUN", 'name' => "Cundinamarca", 'idCountry' => 49],
            ['id' => 148, 'iso' => "CO-GUA", 'name' => "GuainÃ­a", 'idCountry' => 49],
            ['id' => 149, 'iso' => "CO-GUV", 'name' => "Guaviare", 'idCountry' => 49],
            ['id' => 151, 'iso' => "CO-LAG", 'name' => "La Guajira", 'idCountry' => 49],
            ['id' => 152, 'iso' => "CO-MAG", 'name' => "Magdalena", 'idCountry' => 49],
            ['id' => 153, 'iso' => "CO-MET", 'name' => "Meta", 'idCountry' => 49],
            ['id' => 154, 'iso' => "CO-NAR", 'name' => "NariÃ±o", 'idCountry' => 49],
            ['id' => 155, 'iso' => "CO-NSA", 'name' => "Norte de Santander", 'idCountry' => 49],
            ['id' => 156, 'iso' => "CO-PUT", 'name' => "Putumayo", 'idCountry' => 49],
            ['id' => 157, 'iso' => "CO-QUI", 'name' => "QuindÃ­o", 'idCountry' => 49],
            ['id' => 158, 'iso' => "CO-RIS", 'name' => "Risaralda", 'idCountry' => 49],
            ['id' => 159, 'iso' => "CO-SAP", 'name' => "San AndrÃ©s y Providencia", 'idCountry' => 49],
            ['id' => 160, 'iso' => "CO-SAN", 'name' => "Santander", 'idCountry' => 49],
            ['id' => 161, 'iso' => "CO-SUC", 'name' => "Sucre", 'idCountry' => 49],
            ['id' => 162, 'iso' => "CO-TOL", 'name' => "Tolima", 'idCountry' => 49],
            ['id' => 163, 'iso' => "CO-VAC", 'name' => "Valle del Cauca", 'idCountry' => 49],
            ['id' => 164, 'iso' => "CO-VAU", 'name' => "VaupÃ©s", 'idCountry' => 49],
            ['id' => 165, 'iso' => "CO-VID", 'name' => "Vichada", 'idCountry' => 49],
            ['id' => 2, 'iso' => "DO-02", 'name' => "Azua", 'idCountry' => 61],
            ['id' => 103, 'iso' => "ES-AN", 'name' => "AndalucÃ­a", 'idCountry' => 68],
            ['id' => 125, 'iso' => "ES-IB", 'name' => "Illes BalearsÂ (ca) [Islas Baleares]", 'idCountry' => 68],
            ['id' => 126, 'iso' => "ES-RI", 'name' => "La Rioja", 'idCountry' => 68],
            ['id' => 127, 'iso' => "ES-MD", 'name' => "Madrid, Comunidad de", 'idCountry' => 68],
            ['id' => 128, 'iso' => "ES-MC", 'name' => "Murcia, RegiÃ³n de", 'idCountry' => 68],
            ['id' => 129, 'iso' => "ES-NC", 'name' => "Navarra, Comunidad Foral de / Nafarroako Foru KomunitateaÂ (eu)", 'idCountry' => 68],
            ['id' => 130, 'iso' => "ES-PV", 'name' => "PaÃ­s Vasco / EuskadiÂ (eu)", 'idCountry' => 68],
            ['id' => 131, 'iso' => "ES-VC", 'name' => "Valenciana, Comunidad / Valenciana, ComunitatÂ (ca)", 'idCountry' => 68],
            ['id' => 132, 'iso' => "ES-CE", 'name' => "Ceuta", 'idCountry' => 68],
            ['id' => 133, 'iso' => "ES-ML", 'name' => "Melilla", 'idCountry' => 68],
            ['id' => 150, 'iso' => "CO-HUI", 'name' => "Huila", 'idCountry' => 49],
            ['id' => 166, 'iso' => "NI-BO", 'name' => "Boaco", 'idCountry' => 165],
            ['id' => 182, 'iso' => "NI-AS", 'name' => "AtlÃ¡ntico Sur", 'idCountry' => 165],
            ['id' => 167, 'iso' => "NI-CA", 'name' => "Carazo", 'idCountry' => 165],
            ['id' => 168, 'iso' => "NI-CI", 'name' => "Chinandega", 'idCountry' => 165],
            ['id' => 169, 'iso' => "NI-CO", 'name' => "Chontales", 'idCountry' => 165],
            ['id' => 170, 'iso' => "NI-ES", 'name' => "EstelÃ­", 'idCountry' => 165],
            ['id' => 171, 'iso' => "NI-GR", 'name' => "Granada", 'idCountry' => 165],
            ['id' => 172, 'iso' => "NI-JI", 'name' => "Jinotega", 'idCountry' => 165],
            ['id' => 173, 'iso' => "NI-LE", 'name' => "LeÃ³n", 'idCountry' => 165],
            ['id' => 174, 'iso' => "NI-MD", 'name' => "Madriz", 'idCountry' => 165],
            ['id' => 175, 'iso' => "NI-MN", 'name' => "Managua", 'idCountry' => 165],
            ['id' => 176, 'iso' => "NI-MS", 'name' => "Masaya", 'idCountry' => 165],
            ['id' => 177, 'iso' => "NI-MT", 'name' => "Matagalpa", 'idCountry' => 165],
            ['id' => 178, 'iso' => "NI-NS", 'name' => "Nueva Segovia", 'idCountry' => 165],
            ['id' => 179, 'iso' => "NI-SJ", 'name' => "RÃ­o San Juan", 'idCountry' => 165],
            ['id' => 180, 'iso' => "NI-RI", 'name' => "Rivas", 'idCountry' => 165],
            ['id' => 181, 'iso' => "NI-AN", 'name' => "AtlÃ¡ntico Norte", 'idCountry' => 165],
            ['id' => 107, 'iso' => "VE-VE", 'name' => "Toda Venezuela", 'idCountry' => 238],
            ['id' => 184, 'iso' => "SV-AH", 'name' => "AhuachapÃ¡n", 'idCountry' => 210],
            ['id' => 185, 'iso' => "SV-CA", 'name' => "CabaÃ±as", 'idCountry' => 210],
            ['id' => 186, 'iso' => "SV-CH", 'name' => "Chalatenango", 'idCountry' => 210],
            ['id' => 187, 'iso' => "SV-CU", 'name' => "CuscatlÃ¡n", 'idCountry' => 210],
            ['id' => 188, 'iso' => "SV-LI", 'name' => "La Libertad", 'idCountry' => 210],
            ['id' => 190, 'iso' => "SV-PA", 'name' => "La Paz", 'idCountry' => 210],
            ['id' => 191, 'iso' => "SV-SA", 'name' => "Santa Ana", 'idCountry' => 210],
            ['id' => 192, 'iso' => "SV-SM", 'name' => "San Miguel", 'idCountry' => 210],
            ['id' => 193, 'iso' => "SV-SO", 'name' => "Sonsonate", 'idCountry' => 210],
            ['id' => 194, 'iso' => "SV-SS", 'name' => "San Salvador", 'idCountry' => 210],
            ['id' => 195, 'iso' => "SV-SV", 'name' => "San Vicente", 'idCountry' => 210],
            ['id' => 196, 'iso' => "SV-UN", 'name' => "La UniÃ³n", 'idCountry' => 210],
            ['id' => 197, 'iso' => "SV-US", 'name' => "UsulutÃ¡n", 'idCountry' => 210],
            ['id' => 189, 'iso' => "SV-MO", 'name' => "MorazÃ¡n", 'idCountry' => 210],
            ['id' => 198, 'iso' => "PE-PE", 'name' => "Todo PerÃº", 'idCountry' => 174],
            ['id' => 199, 'iso' => "EC-EC", 'name' => "Todo Ecuador", 'idCountry' => 63],
            ['id' => 200, 'iso' => "HN-DC", 'name' => "Distrito Central", 'idCountry' => 97],
            ['id' => 201, 'iso' => "HN-AT", 'name' => "AtlÃ¡ntida", 'idCountry' => 97],
            ['id' => 202, 'iso' => "HN-CH", 'name' => "Choluteca", 'idCountry' => 97],
            ['id' => 203, 'iso' => "HN-CL", 'name' => "ColÃ³n", 'idCountry' => 97],
            ['id' => 204, 'iso' => "HN-CM", 'name' => "Comayagua", 'idCountry' => 97],
            ['id' => 205, 'iso' => "HN-CP", 'name' => "CopÃ¡n", 'idCountry' => 97],
            ['id' => 206, 'iso' => "HN-CR", 'name' => "CortÃ©s", 'idCountry' => 97],
            ['id' => 207, 'iso' => "HN-EP", 'name' => "El ParaÃ­so", 'idCountry' => 97],
            ['id' => 208, 'iso' => "HN-FM", 'name' => "Francisco MorazÃ¡n", 'idCountry' => 97],
            ['id' => 209, 'iso' => "HN-GD", 'name' => "Gracias a Dios", 'idCountry' => 97],
            ['id' => 210, 'iso' => "HN-IN", 'name' => "IntibucÃ¡", 'idCountry' => 97],
            ['id' => 211, 'iso' => "HN-IB", 'name' => "Islas de la BahÃ­a", 'idCountry' => 97],
            ['id' => 212, 'iso' => "HN-LP", 'name' => "La Paz", 'idCountry' => 97],
            ['id' => 213, 'iso' => "HN-LM", 'name' => "Lempira", 'idCountry' => 97],
            ['id' => 214, 'iso' => "HN-OC", 'name' => "Ocotepeque", 'idCountry' => 97],
            ['id' => 215, 'iso' => "HN-OL", 'name' => "Olancho", 'idCountry' => 97],
            ['id' => 216, 'iso' => "HN-SB", 'name' => "Santa BÃ¡rbara", 'idCountry' => 97],
            ['id' => 217, 'iso' => "HN-VL", 'name' => "Valle", 'idCountry' => 97],
            ['id' => 218, 'iso' => "HN-YO", 'name' => "Yoro", 'idCountry' => 97],
            ['id' => 219, 'iso' => "PH-ABR", 'name' => "ABRA", 'idCountry' => 177],
            ['id' => 220, 'iso' => "PH-AKL", 'name' => "AKLAN", 'idCountry' => 177],
            ['id' => 221, 'iso' => "PH-ALB", 'name' => "ALBAY", 'idCountry' => 177],
            ['id' => 222, 'iso' => "PH-ANT", 'name' => "ANTIQUE", 'idCountry' => 177],
            ['id' => 223, 'iso' => "PH-BAN", 'name' => "BATAAN", 'idCountry' => 177],
            ['id' => 224, 'iso' => "PH-BTG", 'name' => "BATANGAS", 'idCountry' => 177],
            ['id' => 225, 'iso' => "PH-BEN", 'name' => "BENGUET", 'idCountry' => 177],
            ['id' => 226, 'iso' => "PH-BUL", 'name' => "BULACAN", 'idCountry' => 177],
            ['id' => 227, 'iso' => "PH-CAN", 'name' => "CAMARINES NORTE", 'idCountry' => 177],
            ['id' => 228, 'iso' => "PH-CAS", 'name' => "CAMARINES SUR", 'idCountry' => 177],
            ['id' => 229, 'iso' => "PH-CAP", 'name' => "CAPIZ", 'idCountry' => 177],
            ['id' => 230, 'iso' => "PH-CAV", 'name' => "CAVITE", 'idCountry' => 177],
            ['id' => 231, 'iso' => "PH-CEB", 'name' => "CEBU", 'idCountry' => 177],
            ['id' => 232, 'iso' => "PH-DAV", 'name' => "DAVAO DEL SUR", 'idCountry' => 177],
            ['id' => 233, 'iso' => "PH-ILN", 'name' => "ILOCOS NORTE", 'idCountry' => 177],
            ['id' => 234, 'iso' => "PH-ILS", 'name' => "ILOCOS SUR", 'idCountry' => 177],
            ['id' => 235, 'iso' => "PH-ILI", 'name' => "ILOILO", 'idCountry' => 177],
            ['id' => 236, 'iso' => "PH-ISA", 'name' => "ISABELA", 'idCountry' => 177],
            ['id' => 237, 'iso' => "PH-LUN", 'name' => "LA UNION", 'idCountry' => 177],
            ['id' => 238, 'iso' => "PH-LAG", 'name' => "LAGUNA", 'idCountry' => 177],
            ['id' => 239, 'iso' => "PH-LEY", 'name' => "LEYTE", 'idCountry' => 177],
            ['id' => 240, 'iso' => "PH-MMN", 'name' => "METRO MANILA", 'idCountry' => 177],
            ['id' => 241, 'iso' => "PH-NEC", 'name' => "NEGROS OCCIDENTAL", 'idCountry' => 177],
            ['id' => 242, 'iso' => "PH-NER", 'name' => "NEGROS ORIENTAL", 'idCountry' => 177],
            ['id' => 243, 'iso' => "PH-NUE", 'name' => "NUEVA ECIJA", 'idCountry' => 177],
            ['id' => 244, 'iso' => "PH-NUV", 'name' => "NUEVA VIZCAYA", 'idCountry' => 177],
            ['id' => 245, 'iso' => "PH-PLW", 'name' => "PALAWAN", 'idCountry' => 177],
            ['id' => 246, 'iso' => "PH-PAM", 'name' => "PAMPANGA", 'idCountry' => 177],
            ['id' => 247, 'iso' => "PH-PAN", 'name' => "PANGASINAN", 'idCountry' => 177],
            ['id' => 248, 'iso' => "PH-QUI", 'name' => "QUIRINO", 'idCountry' => 177],
            ['id' => 249, 'iso' => "PH-RIZ", 'name' => "RIZAL", 'idCountry' => 177],
            ['id' => 250, 'iso' => "PH-SUK", 'name' => "SULTAN KUDARAT", 'idCountry' => 177],
            ['id' => 251, 'iso' => "PH-SUR", 'name' => "SURIGAO DEL SUR", 'idCountry' => 177],
            ['id' => 252, 'iso' => "PH-TAR", 'name' => "TARLAC", 'idCountry' => 177],
            ['id' => 253, 'iso' => "PH-TAW", 'name' => "TAWI-TAWI", 'idCountry' => 177],
            ['id' => 254, 'iso' => "PH-ZMB", 'name' => "ZAMBALES", 'idCountry' => 177],
            ['id' => 258, 'iso' => "CO-ALL", 'name' => "Todo Colombia", 'idCountry' => 49],
            ['id' => 259, 'iso' => "AR-ALL", 'name' => "Todo Argentina", 'idCountry' => 10],
            ['id' => 260, 'iso' => "BO-ALL", 'name' => "Todo Bolivia", 'idCountry' => 29],
            ['id' => 261, 'iso' => "BO-C", 'name' => "Cochabamba", 'idCountry' => 29],
            ['id' => 262, 'iso' => "BO-H", 'name' => "Chuquisaca", 'idCountry' => 29],
            ['id' => 263, 'iso' => "BO-B", 'name' => "El Beni", 'idCountry' => 29],
            ['id' => 264, 'iso' => "BO-L", 'name' => "La Paz", 'idCountry' => 29],
            ['id' => 265, 'iso' => "BO-O", 'name' => "Oruro", 'idCountry' => 29],
            ['id' => 266, 'iso' => "BO-N", 'name' => "Pando", 'idCountry' => 29],
            ['id' => 267, 'iso' => "BO-P", 'name' => "PotosÃ­", 'idCountry' => 29],
            ['id' => 268, 'iso' => "BO-S", 'name' => "Santa Cruz", 'idCountry' => 29],
            ['id' => 269, 'iso' => "BO-T", 'name' => "Tarija", 'idCountry' => 29],
            ['id' => 270, 'iso' => "AR-B", 'name' => "Buenos Aires", 'idCountry' => 10],
            ['id' => 271, 'iso' => "AR-K", 'name' => "Catamarca", 'idCountry' => 10],
            ['id' => 272, 'iso' => "AR-H", 'name' => "Chaco", 'idCountry' => 10],
            ['id' => 273, 'iso' => "AR-U", 'name' => "Chubut", 'idCountry' => 10],
            ['id' => 274, 'iso' => "AR-X", 'name' => "CÃ³rdoba", 'idCountry' => 10],
            ['id' => 275, 'iso' => "AR-W", 'name' => "Corrientes", 'idCountry' => 10],
            ['id' => 276, 'iso' => "AR-E", 'name' => "Entre RÃ­os", 'idCountry' => 10],
            ['id' => 277, 'iso' => "AR-P", 'name' => "Formosa", 'idCountry' => 10],
            ['id' => 278, 'iso' => "AR-Y", 'name' => "Jujuy", 'idCountry' => 10],
            ['id' => 279, 'iso' => "AR-L", 'name' => "La Pampa", 'idCountry' => 10],
            ['id' => 280, 'iso' => "AR-F", 'name' => "La Rioja", 'idCountry' => 10],
            ['id' => 281, 'iso' => "AR-M", 'name' => "Mendoza", 'idCountry' => 10],
            ['id' => 282, 'iso' => "AR-N", 'name' => "Misiones", 'idCountry' => 10],
            ['id' => 283, 'iso' => "AR-Q", 'name' => "NeuquÃ©n", 'idCountry' => 10],
            ['id' => 284, 'iso' => "AR-R", 'name' => "RÃ­o Negro", 'idCountry' => 10],
            ['id' => 285, 'iso' => "AR-A", 'name' => "Salta", 'idCountry' => 10],
            ['id' => 286, 'iso' => "AR-J", 'name' => "San Juan", 'idCountry' => 10],
            ['id' => 287, 'iso' => "AR-D", 'name' => "San Luis", 'idCountry' => 10],
            ['id' => 288, 'iso' => "AR-Z", 'name' => "Santa Cruz", 'idCountry' => 10],
            ['id' => 289, 'iso' => "AR-S", 'name' => "Santa Fe", 'idCountry' => 10],
            ['id' => 290, 'iso' => "AR-G", 'name' => "Santiago del Estero", 'idCountry' => 10],
            ['id' => 291, 'iso' => "AR-V", 'name' => "Tierra del Fuego", 'idCountry' => 10],
            ['id' => 292, 'iso' => "AR-T", 'name' => "TucumÃ¡n", 'idCountry' => 10],
            ['id' => 293, 'iso' => "EC-A", 'name' => "Azuay", 'idCountry' => 63],
            ['id' => 294, 'iso' => "EC-B", 'name' => "BolÃ­var", 'idCountry' => 63],
            ['id' => 295, 'iso' => "EC-F", 'name' => "CaÃ±ar", 'idCountry' => 63],
            ['id' => 296, 'iso' => "EC-C", 'name' => "Carchi", 'idCountry' => 63],
            ['id' => 297, 'iso' => "EC-H", 'name' => "Chimborazo", 'idCountry' => 63],
            ['id' => 298, 'iso' => "EC-X", 'name' => "Cotopaxi", 'idCountry' => 63],
            ['id' => 299, 'iso' => "EC-O", 'name' => "El Oro", 'idCountry' => 63],
            ['id' => 300, 'iso' => "EC-E", 'name' => "Esmeraldas", 'idCountry' => 63],
            ['id' => 301, 'iso' => "EC-W", 'name' => "GalÃ¡pagos", 'idCountry' => 63],
            ['id' => 302, 'iso' => "EC-G", 'name' => "Guayas", 'idCountry' => 63],
            ['id' => 303, 'iso' => "EC-I", 'name' => "Imbabura", 'idCountry' => 63],
            ['id' => 304, 'iso' => "EC-L", 'name' => "Loja", 'idCountry' => 63],
            ['id' => 305, 'iso' => "EC-R", 'name' => "Los RÃ­os", 'idCountry' => 63],
            ['id' => 306, 'iso' => "EC-M", 'name' => "ManabÃ­", 'idCountry' => 63],
            ['id' => 307, 'iso' => "EC-S", 'name' => "Morona-Santiago", 'idCountry' => 63],
            ['id' => 308, 'iso' => "EC-N", 'name' => "Napo", 'idCountry' => 63],
            ['id' => 309, 'iso' => "EC-D", 'name' => "Orellana", 'idCountry' => 63],
            ['id' => 310, 'iso' => "EC-Y", 'name' => "Pastaza", 'idCountry' => 63],
            ['id' => 311, 'iso' => "EC-P", 'name' => "Pichincha", 'idCountry' => 63],
            ['id' => 312, 'iso' => "EC-SE", 'name' => "Santa Elena", 'idCountry' => 63],
            ['id' => 313, 'iso' => "EC-SD", 'name' => "Santo Domingo de los TsÃ¡chilas", 'idCountry' => 63],
            ['id' => 314, 'iso' => "EC-U", 'name' => "SucumbÃ­os", 'idCountry' => 63],
            ['id' => 315, 'iso' => "EC-T", 'name' => "Tungurahua", 'idCountry' => 63],
            ['id' => 316, 'iso' => "EC-Z", 'name' => "Zamora-Chinchipe", 'idCountry' => 63],
            ['id' => 317, 'iso' => "PE-LMA", 'name' => "Lima", 'idCountry' => 174],
            ['id' => 318, 'iso' => "PE-AMA", 'name' => "Amazonas", 'idCountry' => 174],
            ['id' => 319, 'iso' => "PE-ANC", 'name' => "Ancash", 'idCountry' => 174],
            ['id' => 320, 'iso' => "PE-APU", 'name' => "ApurÃ­mac", 'idCountry' => 174],
            ['id' => 321, 'iso' => "PE-ARE", 'name' => "Arequipa", 'idCountry' => 174],
            ['id' => 322, 'iso' => "PE-AYA", 'name' => "Ayacucho", 'idCountry' => 174],
            ['id' => 323, 'iso' => "PE-CAJ", 'name' => "Cajamarca", 'idCountry' => 174],
            ['id' => 324, 'iso' => "PE-CUS", 'name' => "Cusco", 'idCountry' => 174],
            ['id' => 325, 'iso' => "PE-CAL", 'name' => "El Callao", 'idCountry' => 174],
            ['id' => 326, 'iso' => "PE-HUV", 'name' => "Huancavelica", 'idCountry' => 174],
            ['id' => 327, 'iso' => "PE-HUC", 'name' => "HuÃ¡nuco", 'idCountry' => 174],
            ['id' => 328, 'iso' => "PE-ICA", 'name' => "Ica", 'idCountry' => 174],
            ['id' => 329, 'iso' => "PE-JUN", 'name' => "JunÃ­n", 'idCountry' => 174],
            ['id' => 330, 'iso' => "PE-LAL", 'name' => "La Libertad", 'idCountry' => 174],
            ['id' => 331, 'iso' => "PE-LAM", 'name' => "Lambayeque", 'idCountry' => 174],
            ['id' => 332, 'iso' => "PE-LIM", 'name' => "Lima", 'idCountry' => 174],
            ['id' => 333, 'iso' => "PE-LOR", 'name' => "Loreto", 'idCountry' => 174],
            ['id' => 334, 'iso' => "PE-MDD", 'name' => "Madre de Dios", 'idCountry' => 174],
            ['id' => 335, 'iso' => "PE-MOQ", 'name' => "Moquegua", 'idCountry' => 174],
            ['id' => 336, 'iso' => "PE-PAS", 'name' => "Pasco", 'idCountry' => 174],
            ['id' => 337, 'iso' => "PE-PIU", 'name' => "Piura", 'idCountry' => 174],
            ['id' => 338, 'iso' => "PE-PUN", 'name' => "Puno", 'idCountry' => 174],
            ['id' => 339, 'iso' => "PE-SAM", 'name' => "San MartÃ­n", 'idCountry' => 174],
            ['id' => 340, 'iso' => "PE-TAC", 'name' => "Tacna", 'idCountry' => 174],
            ['id' => 341, 'iso' => "PE-TUM", 'name' => "Tumbes", 'idCountry' => 174],
            ['id' => 342, 'iso' => "PE-UCA", 'name' => "Ucayali  ", 'idCountry' => 174],
            ['id' => 343, 'iso' => "PA-10", 'name' => "PanamÃ¡ Oeste", 'idCountry' => 173],
            ['id' => 344, 'iso' => "DO-ALL", 'name' => "Todo el Pais", 'idCountry' => 61],
            ['id' => 345, 'iso' => "MX-AGU", 'name' => "Aguascalientes", 'idCountry' => 157],
            ['id' => 346, 'iso' => "MX-BCN", 'name' => "Baja California", 'idCountry' => 157],
            ['id' => 347, 'iso' => "MX-BCS", 'name' => "Baja California Sur", 'idCountry' => 157],
            ['id' => 348, 'iso' => "MX-CAM", 'name' => "Campeche", 'idCountry' => 157],
            ['id' => 349, 'iso' => "MX-COA", 'name' => "Coahuila", 'idCountry' => 157],
            ['id' => 350, 'iso' => "MX-COL", 'name' => "Colima", 'idCountry' => 157],
            ['id' => 351, 'iso' => "MX-CHP", 'name' => "Chiapas", 'idCountry' => 157],
            ['id' => 352, 'iso' => "MX-CHH", 'name' => "Chihuahua", 'idCountry' => 157],
            ['id' => 353, 'iso' => "MX-DUR", 'name' => "Durango", 'idCountry' => 157],
            ['id' => 354, 'iso' => "MX-GUA", 'name' => "Guanajuato", 'idCountry' => 157],
            ['id' => 355, 'iso' => "MX-GRO", 'name' => "Guerrero", 'idCountry' => 157],
            ['id' => 356, 'iso' => "MX-HID", 'name' => "Hidalgo", 'idCountry' => 157],
            ['id' => 357, 'iso' => "MX-JAL", 'name' => "Jalisco", 'idCountry' => 157],
            ['id' => 358, 'iso' => "MX-MEX", 'name' => "MÃ©xico", 'idCountry' => 157],
            ['id' => 359, 'iso' => "MX-MIC", 'name' => "MichoacÃ¡n", 'idCountry' => 157],
            ['id' => 360, 'iso' => "MX-MOR", 'name' => "Morelos", 'idCountry' => 157],
            ['id' => 361, 'iso' => "MX-NAY", 'name' => "Nayarit", 'idCountry' => 157],
            ['id' => 362, 'iso' => "MX-NLE", 'name' => "Nuevo LeÃ³n", 'idCountry' => 157],
            ['id' => 363, 'iso' => "MX-OAX", 'name' => "Oaxaca", 'idCountry' => 157],
            ['id' => 364, 'iso' => "MX-PUE", 'name' => "Puebla", 'idCountry' => 157],
            ['id' => 365, 'iso' => "MX-QUE", 'name' => "QuerÃ©taro", 'idCountry' => 157],
            ['id' => 366, 'iso' => "MX-ROO", 'name' => "Quintana Roo", 'idCountry' => 157],
            ['id' => 367, 'iso' => "MX-SLP", 'name' => "San Luis PotosÃ­", 'idCountry' => 157],
            ['id' => 368, 'iso' => "MX-SIN", 'name' => "Sinaloa", 'idCountry' => 157],
            ['id' => 369, 'iso' => "MX-SON", 'name' => "Sonora", 'idCountry' => 157],
            ['id' => 370, 'iso' => "MX-TAB", 'name' => "Tabasco", 'idCountry' => 157],
            ['id' => 371, 'iso' => "MX-TAM", 'name' => "Tamaulipas", 'idCountry' => 157],
            ['id' => 372, 'iso' => "MX-TLA", 'name' => "Tlaxcala", 'idCountry' => 157],
            ['id' => 373, 'iso' => "MX-VER", 'name' => "Veracruz", 'idCountry' => 157],
            ['id' => 374, 'iso' => "MX-YUC", 'name' => "YucatÃ¡n", 'idCountry' => 157],
            ['id' => 375, 'iso' => "MX-ZAC", 'name' => "Zacatecas", 'idCountry' => 157],
            ['id' => 376, 'iso' => "CU-15", 'name' => "Artemisa", 'idCountry' => 51],
            ['id' => 377, 'iso' => "CU-09", 'name' => "CamagÃ¼ey", 'idCountry' => 51],
            ['id' => 378, 'iso' => "CU-08", 'name' => "Ciego de Ãvila", 'idCountry' => 51],
            ['id' => 379, 'iso' => "CU-06", 'name' => "Cienfuegos", 'idCountry' => 51],
            ['id' => 380, 'iso' => "CU-12", 'name' => "Granma", 'idCountry' => 51],
            ['id' => 381, 'iso' => "CU-14", 'name' => "GuantÃ¡namo", 'idCountry' => 51],
            ['id' => 382, 'iso' => "CU-11", 'name' => "HolguÃ­n", 'idCountry' => 51],
            ['id' => 383, 'iso' => "CU-03", 'name' => "La Habana", 'idCountry' => 51],
            ['id' => 384, 'iso' => "CU-10", 'name' => "Las Tunas", 'idCountry' => 51],
            ['id' => 385, 'iso' => "CU-04", 'name' => "Matanzas", 'idCountry' => 51],
            ['id' => 386, 'iso' => "CU-16", 'name' => "Mayabeque", 'idCountry' => 51],
            ['id' => 387, 'iso' => "CU-01", 'name' => "Pinar del RÃ­o", 'idCountry' => 51],
            ['id' => 388, 'iso' => "CU-07", 'name' => "Sancti SpÃ­ritus", 'idCountry' => 51],
            ['id' => 389, 'iso' => "CU-13", 'name' => "Santiago de Cuba", 'idCountry' => 51],
            ['id' => 390, 'iso' => "CU-05", 'name' => "Villa Clara", 'idCountry' => 51],
            ['id' => 391, 'iso' => "CU-99", 'name' => "Isla de la Juventud", 'idCountry' => 51],
            ['id' => 392, 'iso' => "US-XX", 'name' => "TODO USA", 'idCountry' => 233],
            ['id' => 393, 'iso' => "TN", 'name' => "Todo Nicaragua", 'idCountry' => 165],
            ['id' => 394, 'iso' => "CL-AI", 'name' => "AysÃ©n", 'idCountry' => 46],
            ['id' => 395, 'iso' => "CL-AN", 'name' => "Antofagasta", 'idCountry' => 46],
            ['id' => 396, 'iso' => "CL-AR", 'name' => "AraucanÃ­a", 'idCountry' => 46],
            ['id' => 397, 'iso' => "CL-AP", 'name' => "Arica y Parinacota", 'idCountry' => 46],
            ['id' => 398, 'iso' => "CL-AT", 'name' => "Atacama", 'idCountry' => 46],
            ['id' => 399, 'iso' => "CL-BI", 'name' => "BiobÃ­o", 'idCountry' => 46],
            ['id' => 400, 'iso' => "CL-CO", 'name' => "Coquimbo", 'idCountry' => 46],
            ['id' => 401, 'iso' => "CL-LI", 'name' => "Libertador General Bernardo O Higgins", 'idCountry' => 46],
            ['id' => 402, 'iso' => "CL-LL", 'name' => "Los Lagos", 'idCountry' => 46],
            ['id' => 403, 'iso' => "CL-LR", 'name' => "Los RÃ­os", 'idCountry' => 46],
            ['id' => 404, 'iso' => "CL-MA", 'name' => "Magallanes", 'idCountry' => 46],
            ['id' => 405, 'iso' => "CL-ML", 'name' => "Maule", 'idCountry' => 46],
            ['id' => 406, 'iso' => "CL-RM", 'name' => "RegiÃ³n Metropolitana de Santiago", 'idCountry' => 46],
            ['id' => 407, 'iso' => "CL-TA", 'name' => "TarapacÃ¡", 'idCountry' => 46],
            ['id' => 408, 'iso' => "CL-VS", 'name' => "ValparaÃ­so", 'idCountry' => 46],
            ['id' => 409, 'iso' => "CL-ALL", 'name' => "Todo Chile", 'idCountry' => 46],
            ['id' => 410, 'iso' => "GT-AV", 'name' => "Alta Verapaz", 'idCountry' => 91],
            ['id' => 411, 'iso' => "GT-BV", 'name' => "Baja Verapaz", 'idCountry' => 91],
            ['id' => 412, 'iso' => "GT-CM", 'name' => "Chimaltenango", 'idCountry' => 91],
            ['id' => 413, 'iso' => "GT-CQ", 'name' => "Chiquimula", 'idCountry' => 91],
            ['id' => 414, 'iso' => "GT-PR", 'name' => "El Progreso", 'idCountry' => 91],
            ['id' => 415, 'iso' => "GT-ES", 'name' => "Escuintla", 'idCountry' => 91],
            ['id' => 416, 'iso' => "GT-GU", 'name' => "Guatemala", 'idCountry' => 91],
            ['id' => 417, 'iso' => "GT-HU", 'name' => "Huehuetenango", 'idCountry' => 91],
            ['id' => 418, 'iso' => "GT-IZ", 'name' => "Izabal", 'idCountry' => 91],
            ['id' => 419, 'iso' => "GT-JA", 'name' => "Jalapa", 'idCountry' => 91],
            ['id' => 420, 'iso' => "GT-JU", 'name' => "Jutiapa", 'idCountry' => 91],
            ['id' => 421, 'iso' => "GT-PE", 'name' => "PetÃ©n", 'idCountry' => 91],
            ['id' => 422, 'iso' => "GT-QZ", 'name' => "Quetzaltenango", 'idCountry' => 91],
            ['id' => 423, 'iso' => "GT-QC", 'name' => "QuichÃ©", 'idCountry' => 91],
            ['id' => 424, 'iso' => "GT-RE", 'name' => "Retalhuleu", 'idCountry' => 91],
            ['id' => 425, 'iso' => "GT-SA", 'name' => "SacatepÃ©quez", 'idCountry' => 91],
            ['id' => 426, 'iso' => "GT-SM", 'name' => "San Marcos", 'idCountry' => 91],
            ['id' => 427, 'iso' => "GT-SR", 'name' => "Santa Rosa", 'idCountry' => 91],
            ['id' => 428, 'iso' => "GT-SO", 'name' => "SololÃ¡", 'idCountry' => 91],
            ['id' => 429, 'iso' => "GT-SU", 'name' => "SuchitepÃ©quez", 'idCountry' => 91],
            ['id' => 430, 'iso' => "GT-TO", 'name' => "TotonicapÃ¡n", 'idCountry' => 91],
            ['id' => 431, 'iso' => "GT-ZA", 'name' => "Zacapa", 'idCountry' => 91],
            ['id' => 432, 'iso' => "CR-A", 'name' => "Alajuela", 'idCountry' => 50],
            ['id' => 433, 'iso' => "CR-C", 'name' => "Cartago", 'idCountry' => 50],
            ['id' => 434, 'iso' => "CR-G", 'name' => "Guanacaste", 'idCountry' => 50],
            ['id' => 435, 'iso' => "CR-H", 'name' => "Heredia", 'idCountry' => 50],
            ['id' => 436, 'iso' => "CR-L", 'name' => "Limon", 'idCountry' => 50],
            ['id' => 437, 'iso' => "CR-P", 'name' => "Puntarenas", 'idCountry' => 50],
            ['id' => 438, 'iso' => "CR-SJ", 'name' => "San JosÃ©", 'idCountry' => 50],
            ['id' => 439, 'iso' => "CR-ALL", 'name' => "Todo Costa Rica", 'idCountry' => 50],
            ['id' => 440, 'iso' => "HT-AR", 'name' => "Artibonito", 'idCountry' => 99],
            ['id' => 441, 'iso' => "HT-CE", 'name' => "Centro", 'idCountry' => 99],
            ['id' => 442, 'iso' => "HT-GA", 'name' => "Grand Anse", 'idCountry' => 99],
            ['id' => 443, 'iso' => "HT-NI", 'name' => "Nippes", 'idCountry' => 99],
            ['id' => 444, 'iso' => "HT-ND", 'name' => "Norte", 'idCountry' => 99],
            ['id' => 445, 'iso' => "HT-NE", 'name' => "Nordeste", 'idCountry' => 99],
            ['id' => 446, 'iso' => "HT-NO", 'name' => "Noroeste", 'idCountry' => 99],
            ['id' => 447, 'iso' => "HT-OU", 'name' => "Oeste", 'idCountry' => 99],
            ['id' => 448, 'iso' => "HT-SD", 'name' => "Sur", 'idCountry' => 99],
            ['id' => 449, 'iso' => "HT-SE", 'name' => "Sureste", 'idCountry' => 99],
            ['id' => 450, 'iso' => "GT-ALL", 'name' => "Todo Guatemala", 'idCountry' => 91],
            ['id' => 451, 'iso' => "SV-ALL", 'name' => "Todo El Salvador", 'idCountry' => 210],
            ['id' => 452, 'iso' => "VE-W", 'name' => "Dependencias Federales", 'idCountry' => 238],
            ['id' => 453, 'iso' => "VE-A", 'name' => "Distrito Capital", 'idCountry' => 238],
            ['id' => 454, 'iso' => "VE-Z", 'name' => "Amazonas", 'idCountry' => 238],
            ['id' => 455, 'iso' => "VE-B", 'name' => "AnzoÃ¡tegui", 'idCountry' => 238],
            ['id' => 456, 'iso' => "VE-C", 'name' => "Apure", 'idCountry' => 238],
            ['id' => 457, 'iso' => "VE-D", 'name' => "Aragua", 'idCountry' => 238],
            ['id' => 458, 'iso' => "VE-E", 'name' => "Barinas", 'idCountry' => 238],
            ['id' => 459, 'iso' => "VE-F", 'name' => "BolÃ­var", 'idCountry' => 238],
            ['id' => 460, 'iso' => "VE-G", 'name' => "Carabobo", 'idCountry' => 238],
            ['id' => 461, 'iso' => "VE-H", 'name' => "Cojedes", 'idCountry' => 238],
            ['id' => 462, 'iso' => "VE-Y", 'name' => "Delta Amacuro", 'idCountry' => 238],
            ['id' => 463, 'iso' => "VE-I", 'name' => "FalcÃ³n", 'idCountry' => 238],
            ['id' => 464, 'iso' => "VE-J", 'name' => "GuÃ¡rico", 'idCountry' => 238],
            ['id' => 465, 'iso' => "VE-K", 'name' => "Lara", 'idCountry' => 238],
            ['id' => 466, 'iso' => "VE-L", 'name' => "MÃ©rida", 'idCountry' => 238],
            ['id' => 467, 'iso' => "VE-M", 'name' => "Miranda", 'idCountry' => 238],
            ['id' => 468, 'iso' => "VE-N", 'name' => "Monagas", 'idCountry' => 238],
            ['id' => 469, 'iso' => "VE-O", 'name' => "Nueva Esparta", 'idCountry' => 238],
            ['id' => 470, 'iso' => "VE-P", 'name' => "Portuguesa", 'idCountry' => 238],
            ['id' => 471, 'iso' => "VE-R", 'name' => "Sucre", 'idCountry' => 238],
            ['id' => 472, 'iso' => "VE-S", 'name' => "TÃ¡chira", 'idCountry' => 238],
            ['id' => 473, 'iso' => "VE-T", 'name' => "Trujillo", 'idCountry' => 238],
            ['id' => 474, 'iso' => "VE-X", 'name' => "Vargas", 'idCountry' => 238],
            ['id' => 475, 'iso' => "VE-U", 'name' => "Yaracuy", 'idCountry' => 238],
            ['id' => 476, 'iso' => "VE-V", 'name' => "Zulia", 'idCountry' => 238],
        ]);
    }
}
